"""Python models, Pkl loading, and standalone hosting for Tangram apps."""

from .errors import (
    AmbiguousActionError,
    CapabilityGraphError,
    CapabilityGraphStaleError,
    ConfirmationRequiredError,
    DriverError,
    HttpResponseError,
    InputValidationError,
    ManifestDecodeError,
    ManifestCompilationError,
    ManifestValidationError,
    BackendContractError,
    LocalRuntimeError,
    OutputValidationError,
    PklEvaluationError,
    PklNotFoundError,
    PolicyDeniedError,
    RequestRenderError,
    TangramAppError,
    UnknownBindingError,
    UnsupportedRequirementError,
)
from .app import TangramApp, ToolDefinition
from .local_runtime import BackendSpec, LocalAppSession, LocalSourceRuntime
from .project import TangramProject
from .host import (
    AuditEvent,
    ExecutionDriver,
    InMemoryDriver,
    JsonlAuditSink,
    MemoryAuditSink,
    NullAuditSink,
    TangramHost,
)
from .http_driver import (
    HttpExecutionDriver,
    LocalHttpDriver,
    OpenApiRequestRenderer,
    RenderedHttpRequest,
)
from .models import (
    Action,
    ActionBinding,
    ActionCapability,
    CapabilityEffect,
    CapabilityGraph,
    Effect,
    InputBinding,
    OperationBinding,
    PackageIdentity,
)
from .compiler import CompilationResult, ManifestCompiler, compile_manifest
from .manifest import (
    ActionEffect,
    ActionPresentation,
    AppInfo,
    AppName,
    Application,
    ApplicationType,
    AppResourceTypeDefinition,
    AppResourceTypeVersion,
    BodyField,
    CloudProvider,
    ConfigField,
    ManifestPackage,
    OpenApiMapping,
    PathParam,
    QueryParam,
    ResourceNameExtractor,
    ResourcePrivilegeRequirement,
    ResourceRole,
    ResourceType,
    ResourceTypeAction,
    ResponseField,
)
from .pkl import PklEvaluator, PklManifestLoader
from .policy import (
    AuthorizationPolicy,
    DecisionKind,
    InvocationRequest,
    LocalDevelopmentPolicy,
    PolicyDecision,
    Principal,
)
from .validation import Severity, ValidationFinding, ValidationResult, validate_manifest
from .skills import generate_skill, normalize_skill_name, verify_skill

__all__ = [
    "Action",
    "ActionCapability",
    "ActionEffect",
    "ActionBinding",
    "ActionPresentation",
    "AmbiguousActionError",
    "AuditEvent",
    "AuthorizationPolicy",
    "AppName",
    "AppInfo",
    "Application",
    "ApplicationType",
    "AppResourceTypeDefinition",
    "AppResourceTypeVersion",
    "BackendContractError",
    "BackendSpec",
    "BodyField",
    "CapabilityGraph",
    "CapabilityEffect",
    "CapabilityGraphError",
    "CapabilityGraphStaleError",
    "ConfirmationRequiredError",
    "CloudProvider",
    "ConfigField",
    "DecisionKind",
    "DriverError",
    "HttpExecutionDriver",
    "HttpResponseError",
    "Effect",
    "ExecutionDriver",
    "InMemoryDriver",
    "InputValidationError",
    "InputBinding",
    "InvocationRequest",
    "JsonlAuditSink",
    "LocalDevelopmentPolicy",
    "LocalAppSession",
    "LocalHttpDriver",
    "LocalRuntimeError",
    "LocalSourceRuntime",
    "MemoryAuditSink",
    "ManifestDecodeError",
    "ManifestCompilationError",
    "ManifestValidationError",
    "ManifestPackage",
    "ManifestCompiler",
    "NullAuditSink",
    "OutputValidationError",
    "OpenApiMapping",
    "OperationBinding",
    "OpenApiRequestRenderer",
    "PackageIdentity",
    "PolicyDecision",
    "PolicyDeniedError",
    "Principal",
    "PklEvaluationError",
    "PklEvaluator",
    "PklManifestLoader",
    "PklNotFoundError",
    "PathParam",
    "QueryParam",
    "ResourceNameExtractor",
    "ResourcePrivilegeRequirement",
    "ResourceRole",
    "ResourceType",
    "ResourceTypeAction",
    "RenderedHttpRequest",
    "RequestRenderError",
    "ResponseField",
    "Severity",
    "TangramAppError",
    "TangramApp",
    "TangramProject",
    "TangramHost",
    "ToolDefinition",
    "UnknownBindingError",
    "UnsupportedRequirementError",
    "ValidationFinding",
    "ValidationResult",
    "CompilationResult",
    "compile_manifest",
    "generate_skill",
    "normalize_skill_name",
    "validate_manifest",
    "verify_skill",
]

try:  # single source of truth: installed package metadata
    from importlib.metadata import version as _pkg_version

    __version__ = _pkg_version("tangram-app-sdk")
except Exception:  # editable/uninstalled checkouts
    __version__ = "0.1.0rc1"
